matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd java
    - language: node_js
      node_js:
        - "iojs"
        - "7"
      before_script:
        - cd node
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd java/loan-app
