server:
  port: ${PORT:8082}

# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://user:password@${EUREKA_SERVER:eureka-server}:8761/eureka/

# custom attribute for the actuator info endpoint
info:
  app:
    name: client-service
    
# give the application a name
spring:
  application:
    name: client-service
    
# disable actuagor security for endpoints 
management:
  security:
    enabled: false

# custom logging settings
logging:
  level:
      - ".=info"
      - "ar.edu.utn.frre.dacs.loan.client=debug"
      - "org.springframework=info"

# Ribbon is enabled
ribbon:
  eureka:
    enabled: true