server:
  port: ${PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
      - ".=info"
      - "ar.edu.utn.frre.dacs.ms=debug"
      - "org.springframework=info"    