version: '3'
services:
  eureka-server:
    build:
      context:
        ./eureka-server
    ports:
      - 8761:8761
    restart: unless-stopped
    networks:
      - loan-net

  client-service:
    build:
      context:
        ./client-service
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
      - eureka-server
    links:
      - eureka-server
      - mysql01
    networks:
      - loan-net

  savings-account-service:
    build:
      context:
        ./savings-account-service
    ports:
      - 8083:8083
    restart: unless-stopped
    depends_on:
      - eureka-server
    links:
      - eureka-server
      - mysql02
    networks:
      - loan-net

  mysql01:
    image: mysql:latest
    networks:
      - loan-net
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=client-db
    volumes:
      - mysql01-volume:/var/lib/mysql

  mysql02:
    image: mysql:latest
    networks:
      - loan-net
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=savings-account-db
    volumes:
      - mysql02-volume:/var/lib/mysql

  # Zuul API Gateway
  api-gateway:
    build:
      context:
        ./api-gateway
    ports:
      - 8765:8765
    restart: unless-stopped
    networks:
      - loan-net
    depends_on:
      - client-service
      - savings-account-service

  # Zipkin
  zipkin-server:
    build:
      context:
        ./zipkin-server
    ports:
      - 9411:9411
    restart: unless-stopped
    networks:
      - loan-net

  # Turbine
  turbine:
    build:
      context:
        ./turbine
    ports:
      - 8092:8092
    restart: unless-stopped
    networks:
      - loan-net
    links:
      - eureka-server
      - savings-account-service
      - client-service

  # Hystrix Dashboard
  hystrix-dashboard:
    build:
      context:
        ./hystrix-dashboard
    ports:
      - 8090:8090
    restart: unless-stopped
    networks:
      - loan-net
    links:
      - turbine

networks:
  loan-net:
    driver: overlay

volumes:
  mysql01-volume:
  mysql02-volume:
