server:  
  port: ${PORT:8888}

# Configuration of a local Git-repo for development locally without Docker
# note that we are still using git; We just access the git-repo via file: protocol
spring.cloud.config.server.git.uri: https://github.com/jorgevillaverde/config-repo.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@${EUREKA_SERVER:eureka-server}:8761/eureka/

spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest  

logging:
  level:
    root: WARN
    se.callista: INFO

    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO
    org.apache.catalina.session.ManagerBase: INFO

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO
